### ISSUE TITLE
bug tampilan

### ISSUE THREAD

**Issue by ArifDev-coder** [flaxencraft/flaxen#2]
Tampilan tidak responsive. Pada beberapa layar device lain icon pada _halaman web dan tulisan tidak simetris._

**Comment by ArifDev-coder** [comment]
Kami akan segera memperbaiki bug tersebut segera. :)

**Comment by ArifDev-coder** [comment]
![Uploading Screenshot 2024-08-12 221237.png…]()

**Comment by ArifDev-coder** [comment]
[![Screenshot-2024-08-12-221237.png](https://i.postimg.cc/g023yLzJ/Screenshot-2024-08-12-221237.png)](https://postimg.cc/5XDHb0Fd)

**Comment by flaxencraft** [comment]
mantap

**Comment by ArifDev-coder** [comment]
ada bug kok mantap min?

**Comment by ArifDev-coder** [comment]
Bug Fixed!

**Comment by ArifDev-coder** [comment]
mantap
